version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./certbot/etc:/certs:ro  
    networks:
      - web

  redis:
    image: redis:7
    container_name: redis
    networks:
        - web
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
        - web
  gateway:
    build: ./backend/gateway
    image: gateway-image
    container_name: gateway
    command: sh -c "sleep 10 && npx prisma migrate dev --name init && npm run start "
    networks:
        - web
    volumes:
      - ./uploads:/tmp/
    
  user:
    build: ./backend/services/user
    image: user-image
    container_name: user
    command: sh -c "sleep 10 && npx prisma migrate dev --name init && npm run start "
    networks:
        - web
  chat:
    build: ./backend/services/chat
    image: chat-image
    container_name: chat
    command: sh -c "sleep 15 && npx prisma migrate dev --name init && npm run start "
    networks: 
        - web
  notify:
    build: ./backend/services/notify
    image: notify-image
    container_name: notify
    command: sh -c "sleep 20 && npm run start "
    networks: 
        - web
  # game:
  #   build: ./backend/services/game
  #   image: game-image
  #   container_name: game
  #   command: sh -c "npx prisma migrate dev --name init && npm run start "
  #   networks: 
  #       - web

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: